# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.equipment_api import EquipmentApi  # noqa: E501


class TestEquipmentApi(unittest.TestCase):
    """EquipmentApi unit test stubs"""

    def setUp(self):
        self.api = EquipmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_equipment_chassis_by_moid(self):
        """Test case for get_equipment_chassis_by_moid

        Read a 'equipment.Chassis' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_chassis_identity_by_moid(self):
        """Test case for get_equipment_chassis_identity_by_moid

        Read a 'equipment.ChassisIdentity' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_chassis_identity_list(self):
        """Test case for get_equipment_chassis_identity_list

        Read a 'equipment.ChassisIdentity' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_chassis_list(self):
        """Test case for get_equipment_chassis_list

        Read a 'equipment.Chassis' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_device_summary_by_moid(self):
        """Test case for get_equipment_device_summary_by_moid

        Read a 'equipment.DeviceSummary' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_device_summary_list(self):
        """Test case for get_equipment_device_summary_list

        Read a 'equipment.DeviceSummary' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fan_by_moid(self):
        """Test case for get_equipment_fan_by_moid

        Read a 'equipment.Fan' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fan_list(self):
        """Test case for get_equipment_fan_list

        Read a 'equipment.Fan' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fan_module_by_moid(self):
        """Test case for get_equipment_fan_module_by_moid

        Read a 'equipment.FanModule' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fan_module_list(self):
        """Test case for get_equipment_fan_module_list

        Read a 'equipment.FanModule' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_by_moid(self):
        """Test case for get_equipment_fex_by_moid

        Read a 'equipment.Fex' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_identity_by_moid(self):
        """Test case for get_equipment_fex_identity_by_moid

        Read a 'equipment.FexIdentity' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_identity_list(self):
        """Test case for get_equipment_fex_identity_list

        Read a 'equipment.FexIdentity' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_list(self):
        """Test case for get_equipment_fex_list

        Read a 'equipment.Fex' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_operation_by_moid(self):
        """Test case for get_equipment_fex_operation_by_moid

        Read a 'equipment.FexOperation' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_fex_operation_list(self):
        """Test case for get_equipment_fex_operation_list

        Read a 'equipment.FexOperation' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_identity_summary_by_moid(self):
        """Test case for get_equipment_identity_summary_by_moid

        Read a 'equipment.IdentitySummary' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_identity_summary_list(self):
        """Test case for get_equipment_identity_summary_list

        Read a 'equipment.IdentitySummary' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_card_by_moid(self):
        """Test case for get_equipment_io_card_by_moid

        Read a 'equipment.IoCard' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_card_list(self):
        """Test case for get_equipment_io_card_list

        Read a 'equipment.IoCard' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_card_operation_by_moid(self):
        """Test case for get_equipment_io_card_operation_by_moid

        Read a 'equipment.IoCardOperation' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_card_operation_list(self):
        """Test case for get_equipment_io_card_operation_list

        Read a 'equipment.IoCardOperation' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_expander_by_moid(self):
        """Test case for get_equipment_io_expander_by_moid

        Read a 'equipment.IoExpander' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_io_expander_list(self):
        """Test case for get_equipment_io_expander_list

        Read a 'equipment.IoExpander' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_locator_led_by_moid(self):
        """Test case for get_equipment_locator_led_by_moid

        Read a 'equipment.LocatorLed' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_locator_led_list(self):
        """Test case for get_equipment_locator_led_list

        Read a 'equipment.LocatorLed' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_psu_by_moid(self):
        """Test case for get_equipment_psu_by_moid

        Read a 'equipment.Psu' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_psu_control_by_moid(self):
        """Test case for get_equipment_psu_control_by_moid

        Read a 'equipment.PsuControl' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_psu_control_list(self):
        """Test case for get_equipment_psu_control_list

        Read a 'equipment.PsuControl' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_psu_list(self):
        """Test case for get_equipment_psu_list

        Read a 'equipment.Psu' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_rack_enclosure_by_moid(self):
        """Test case for get_equipment_rack_enclosure_by_moid

        Read a 'equipment.RackEnclosure' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_rack_enclosure_list(self):
        """Test case for get_equipment_rack_enclosure_list

        Read a 'equipment.RackEnclosure' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_rack_enclosure_slot_by_moid(self):
        """Test case for get_equipment_rack_enclosure_slot_by_moid

        Read a 'equipment.RackEnclosureSlot' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_rack_enclosure_slot_list(self):
        """Test case for get_equipment_rack_enclosure_slot_list

        Read a 'equipment.RackEnclosureSlot' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_shared_io_module_by_moid(self):
        """Test case for get_equipment_shared_io_module_by_moid

        Read a 'equipment.SharedIoModule' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_shared_io_module_list(self):
        """Test case for get_equipment_shared_io_module_list

        Read a 'equipment.SharedIoModule' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_switch_card_by_moid(self):
        """Test case for get_equipment_switch_card_by_moid

        Read a 'equipment.SwitchCard' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_switch_card_list(self):
        """Test case for get_equipment_switch_card_list

        Read a 'equipment.SwitchCard' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_system_io_controller_by_moid(self):
        """Test case for get_equipment_system_io_controller_by_moid

        Read a 'equipment.SystemIoController' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_system_io_controller_list(self):
        """Test case for get_equipment_system_io_controller_list

        Read a 'equipment.SystemIoController' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_tpm_by_moid(self):
        """Test case for get_equipment_tpm_by_moid

        Read a 'equipment.Tpm' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_tpm_list(self):
        """Test case for get_equipment_tpm_list

        Read a 'equipment.Tpm' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_transceiver_by_moid(self):
        """Test case for get_equipment_transceiver_by_moid

        Read a 'equipment.Transceiver' resource.  # noqa: E501
        """
        pass

    def test_get_equipment_transceiver_list(self):
        """Test case for get_equipment_transceiver_list

        Read a 'equipment.Transceiver' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_chassis(self):
        """Test case for patch_equipment_chassis

        Update a 'equipment.Chassis' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_chassis_identity(self):
        """Test case for patch_equipment_chassis_identity

        Update a 'equipment.ChassisIdentity' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_fan(self):
        """Test case for patch_equipment_fan

        Update a 'equipment.Fan' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_fan_module(self):
        """Test case for patch_equipment_fan_module

        Update a 'equipment.FanModule' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_fex(self):
        """Test case for patch_equipment_fex

        Update a 'equipment.Fex' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_fex_identity(self):
        """Test case for patch_equipment_fex_identity

        Update a 'equipment.FexIdentity' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_fex_operation(self):
        """Test case for patch_equipment_fex_operation

        Update a 'equipment.FexOperation' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_io_card(self):
        """Test case for patch_equipment_io_card

        Update a 'equipment.IoCard' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_io_card_operation(self):
        """Test case for patch_equipment_io_card_operation

        Update a 'equipment.IoCardOperation' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_io_expander(self):
        """Test case for patch_equipment_io_expander

        Update a 'equipment.IoExpander' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_locator_led(self):
        """Test case for patch_equipment_locator_led

        Update a 'equipment.LocatorLed' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_psu(self):
        """Test case for patch_equipment_psu

        Update a 'equipment.Psu' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_psu_control(self):
        """Test case for patch_equipment_psu_control

        Update a 'equipment.PsuControl' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_rack_enclosure(self):
        """Test case for patch_equipment_rack_enclosure

        Update a 'equipment.RackEnclosure' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_rack_enclosure_slot(self):
        """Test case for patch_equipment_rack_enclosure_slot

        Update a 'equipment.RackEnclosureSlot' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_shared_io_module(self):
        """Test case for patch_equipment_shared_io_module

        Update a 'equipment.SharedIoModule' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_switch_card(self):
        """Test case for patch_equipment_switch_card

        Update a 'equipment.SwitchCard' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_system_io_controller(self):
        """Test case for patch_equipment_system_io_controller

        Update a 'equipment.SystemIoController' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_tpm(self):
        """Test case for patch_equipment_tpm

        Update a 'equipment.Tpm' resource.  # noqa: E501
        """
        pass

    def test_patch_equipment_transceiver(self):
        """Test case for patch_equipment_transceiver

        Update a 'equipment.Transceiver' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_chassis(self):
        """Test case for update_equipment_chassis

        Update a 'equipment.Chassis' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_chassis_identity(self):
        """Test case for update_equipment_chassis_identity

        Update a 'equipment.ChassisIdentity' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_fan(self):
        """Test case for update_equipment_fan

        Update a 'equipment.Fan' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_fan_module(self):
        """Test case for update_equipment_fan_module

        Update a 'equipment.FanModule' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_fex(self):
        """Test case for update_equipment_fex

        Update a 'equipment.Fex' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_fex_identity(self):
        """Test case for update_equipment_fex_identity

        Update a 'equipment.FexIdentity' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_fex_operation(self):
        """Test case for update_equipment_fex_operation

        Update a 'equipment.FexOperation' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_io_card(self):
        """Test case for update_equipment_io_card

        Update a 'equipment.IoCard' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_io_card_operation(self):
        """Test case for update_equipment_io_card_operation

        Update a 'equipment.IoCardOperation' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_io_expander(self):
        """Test case for update_equipment_io_expander

        Update a 'equipment.IoExpander' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_locator_led(self):
        """Test case for update_equipment_locator_led

        Update a 'equipment.LocatorLed' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_psu(self):
        """Test case for update_equipment_psu

        Update a 'equipment.Psu' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_psu_control(self):
        """Test case for update_equipment_psu_control

        Update a 'equipment.PsuControl' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_rack_enclosure(self):
        """Test case for update_equipment_rack_enclosure

        Update a 'equipment.RackEnclosure' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_rack_enclosure_slot(self):
        """Test case for update_equipment_rack_enclosure_slot

        Update a 'equipment.RackEnclosureSlot' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_shared_io_module(self):
        """Test case for update_equipment_shared_io_module

        Update a 'equipment.SharedIoModule' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_switch_card(self):
        """Test case for update_equipment_switch_card

        Update a 'equipment.SwitchCard' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_system_io_controller(self):
        """Test case for update_equipment_system_io_controller

        Update a 'equipment.SystemIoController' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_tpm(self):
        """Test case for update_equipment_tpm

        Update a 'equipment.Tpm' resource.  # noqa: E501
        """
        pass

    def test_update_equipment_transceiver(self):
        """Test case for update_equipment_transceiver

        Update a 'equipment.Transceiver' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
