"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.whale import Whale
from openapi_client.model.zebra import Zebra
globals()['Whale'] = Whale
globals()['Zebra'] = Zebra
from openapi_client.model.mammal import Mammal


class TestMammal(unittest.TestCase):
    """Mammal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMammal(self):
        """Test Mammal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Mammal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
