# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.recovery_api import RecoveryApi  # noqa: E501


class TestRecoveryApi(unittest.TestCase):
    """RecoveryApi unit test stubs"""

    def setUp(self):
        self.api = RecoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_recovery_backup_config_policy(self):
        """Test case for create_recovery_backup_config_policy

        Create a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_recovery_backup_profile(self):
        """Test case for create_recovery_backup_profile

        Create a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_create_recovery_on_demand_backup(self):
        """Test case for create_recovery_on_demand_backup

        Create a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_create_recovery_restore(self):
        """Test case for create_recovery_restore

        Create a 'recovery.Restore' resource.  # noqa: E501
        """
        pass

    def test_create_recovery_schedule_config_policy(self):
        """Test case for create_recovery_schedule_config_policy

        Create a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_recovery_backup_config_policy(self):
        """Test case for delete_recovery_backup_config_policy

        Delete a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_recovery_backup_profile(self):
        """Test case for delete_recovery_backup_profile

        Delete a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_delete_recovery_on_demand_backup(self):
        """Test case for delete_recovery_on_demand_backup

        Delete a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_delete_recovery_restore(self):
        """Test case for delete_recovery_restore

        Delete a 'recovery.Restore' resource.  # noqa: E501
        """
        pass

    def test_delete_recovery_schedule_config_policy(self):
        """Test case for delete_recovery_schedule_config_policy

        Delete a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_backup_config_policy_by_moid(self):
        """Test case for get_recovery_backup_config_policy_by_moid

        Read a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_backup_config_policy_list(self):
        """Test case for get_recovery_backup_config_policy_list

        Read a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_backup_profile_by_moid(self):
        """Test case for get_recovery_backup_profile_by_moid

        Read a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_backup_profile_list(self):
        """Test case for get_recovery_backup_profile_list

        Read a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_config_result_by_moid(self):
        """Test case for get_recovery_config_result_by_moid

        Read a 'recovery.ConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_config_result_entry_by_moid(self):
        """Test case for get_recovery_config_result_entry_by_moid

        Read a 'recovery.ConfigResultEntry' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_config_result_entry_list(self):
        """Test case for get_recovery_config_result_entry_list

        Read a 'recovery.ConfigResultEntry' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_config_result_list(self):
        """Test case for get_recovery_config_result_list

        Read a 'recovery.ConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_on_demand_backup_by_moid(self):
        """Test case for get_recovery_on_demand_backup_by_moid

        Read a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_on_demand_backup_list(self):
        """Test case for get_recovery_on_demand_backup_list

        Read a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_restore_by_moid(self):
        """Test case for get_recovery_restore_by_moid

        Read a 'recovery.Restore' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_restore_list(self):
        """Test case for get_recovery_restore_list

        Read a 'recovery.Restore' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_schedule_config_policy_by_moid(self):
        """Test case for get_recovery_schedule_config_policy_by_moid

        Read a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_recovery_schedule_config_policy_list(self):
        """Test case for get_recovery_schedule_config_policy_list

        Read a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_recovery_backup_config_policy(self):
        """Test case for patch_recovery_backup_config_policy

        Update a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_recovery_backup_profile(self):
        """Test case for patch_recovery_backup_profile

        Update a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_patch_recovery_on_demand_backup(self):
        """Test case for patch_recovery_on_demand_backup

        Update a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_patch_recovery_schedule_config_policy(self):
        """Test case for patch_recovery_schedule_config_policy

        Update a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_recovery_backup_config_policy(self):
        """Test case for update_recovery_backup_config_policy

        Update a 'recovery.BackupConfigPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_recovery_backup_profile(self):
        """Test case for update_recovery_backup_profile

        Update a 'recovery.BackupProfile' resource.  # noqa: E501
        """
        pass

    def test_update_recovery_on_demand_backup(self):
        """Test case for update_recovery_on_demand_backup

        Update a 'recovery.OnDemandBackup' resource.  # noqa: E501
        """
        pass

    def test_update_recovery_schedule_config_policy(self):
        """Test case for update_recovery_schedule_config_policy

        Update a 'recovery.ScheduleConfigPolicy' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
