# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.appliance_api import ApplianceApi  # noqa: E501


class TestApplianceApi(unittest.TestCase):
    """ApplianceApi unit test stubs"""

    def setUp(self):
        self.api = ApplianceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_appliance_backup(self):
        """Test case for create_appliance_backup

        Create a 'appliance.Backup' resource.  # noqa: E501
        """
        pass

    def test_create_appliance_backup_policy(self):
        """Test case for create_appliance_backup_policy

        Create a 'appliance.BackupPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_appliance_data_export_policy(self):
        """Test case for create_appliance_data_export_policy

        Create a 'appliance.DataExportPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_appliance_device_claim(self):
        """Test case for create_appliance_device_claim

        Create a 'appliance.DeviceClaim' resource.  # noqa: E501
        """
        pass

    def test_create_appliance_diag_setting(self):
        """Test case for create_appliance_diag_setting

        Create a 'appliance.DiagSetting' resource.  # noqa: E501
        """
        pass

    def test_create_appliance_restore(self):
        """Test case for create_appliance_restore

        Create a 'appliance.Restore' resource.  # noqa: E501
        """
        pass

    def test_delete_appliance_backup(self):
        """Test case for delete_appliance_backup

        Delete a 'appliance.Backup' resource.  # noqa: E501
        """
        pass

    def test_delete_appliance_restore(self):
        """Test case for delete_appliance_restore

        Delete a 'appliance.Restore' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_backup_by_moid(self):
        """Test case for get_appliance_backup_by_moid

        Read a 'appliance.Backup' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_backup_list(self):
        """Test case for get_appliance_backup_list

        Read a 'appliance.Backup' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_backup_policy_by_moid(self):
        """Test case for get_appliance_backup_policy_by_moid

        Read a 'appliance.BackupPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_backup_policy_list(self):
        """Test case for get_appliance_backup_policy_list

        Read a 'appliance.BackupPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_certificate_setting_by_moid(self):
        """Test case for get_appliance_certificate_setting_by_moid

        Read a 'appliance.CertificateSetting' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_certificate_setting_list(self):
        """Test case for get_appliance_certificate_setting_list

        Read a 'appliance.CertificateSetting' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_data_export_policy_by_moid(self):
        """Test case for get_appliance_data_export_policy_by_moid

        Read a 'appliance.DataExportPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_data_export_policy_list(self):
        """Test case for get_appliance_data_export_policy_list

        Read a 'appliance.DataExportPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_device_claim_by_moid(self):
        """Test case for get_appliance_device_claim_by_moid

        Read a 'appliance.DeviceClaim' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_device_claim_list(self):
        """Test case for get_appliance_device_claim_list

        Read a 'appliance.DeviceClaim' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_diag_setting_by_moid(self):
        """Test case for get_appliance_diag_setting_by_moid

        Read a 'appliance.DiagSetting' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_diag_setting_list(self):
        """Test case for get_appliance_diag_setting_list

        Read a 'appliance.DiagSetting' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_image_bundle_by_moid(self):
        """Test case for get_appliance_image_bundle_by_moid

        Read a 'appliance.ImageBundle' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_image_bundle_list(self):
        """Test case for get_appliance_image_bundle_list

        Read a 'appliance.ImageBundle' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_node_info_by_moid(self):
        """Test case for get_appliance_node_info_by_moid

        Read a 'appliance.NodeInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_node_info_list(self):
        """Test case for get_appliance_node_info_list

        Read a 'appliance.NodeInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_release_note_by_moid(self):
        """Test case for get_appliance_release_note_by_moid

        Read a 'appliance.ReleaseNote' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_release_note_list(self):
        """Test case for get_appliance_release_note_list

        Read a 'appliance.ReleaseNote' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_restore_by_moid(self):
        """Test case for get_appliance_restore_by_moid

        Read a 'appliance.Restore' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_restore_list(self):
        """Test case for get_appliance_restore_list

        Read a 'appliance.Restore' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_setup_info_by_moid(self):
        """Test case for get_appliance_setup_info_by_moid

        Read a 'appliance.SetupInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_setup_info_list(self):
        """Test case for get_appliance_setup_info_list

        Read a 'appliance.SetupInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_system_info_by_moid(self):
        """Test case for get_appliance_system_info_by_moid

        Read a 'appliance.SystemInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_system_info_list(self):
        """Test case for get_appliance_system_info_list

        Read a 'appliance.SystemInfo' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_upgrade_by_moid(self):
        """Test case for get_appliance_upgrade_by_moid

        Read a 'appliance.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_upgrade_list(self):
        """Test case for get_appliance_upgrade_list

        Read a 'appliance.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_upgrade_policy_by_moid(self):
        """Test case for get_appliance_upgrade_policy_by_moid

        Read a 'appliance.UpgradePolicy' resource.  # noqa: E501
        """
        pass

    def test_get_appliance_upgrade_policy_list(self):
        """Test case for get_appliance_upgrade_policy_list

        Read a 'appliance.UpgradePolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_backup_policy(self):
        """Test case for patch_appliance_backup_policy

        Update a 'appliance.BackupPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_certificate_setting(self):
        """Test case for patch_appliance_certificate_setting

        Update a 'appliance.CertificateSetting' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_data_export_policy(self):
        """Test case for patch_appliance_data_export_policy

        Update a 'appliance.DataExportPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_diag_setting(self):
        """Test case for patch_appliance_diag_setting

        Update a 'appliance.DiagSetting' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_setup_info(self):
        """Test case for patch_appliance_setup_info

        Update a 'appliance.SetupInfo' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_upgrade(self):
        """Test case for patch_appliance_upgrade

        Update a 'appliance.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_patch_appliance_upgrade_policy(self):
        """Test case for patch_appliance_upgrade_policy

        Update a 'appliance.UpgradePolicy' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_backup_policy(self):
        """Test case for update_appliance_backup_policy

        Update a 'appliance.BackupPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_certificate_setting(self):
        """Test case for update_appliance_certificate_setting

        Update a 'appliance.CertificateSetting' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_data_export_policy(self):
        """Test case for update_appliance_data_export_policy

        Update a 'appliance.DataExportPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_diag_setting(self):
        """Test case for update_appliance_diag_setting

        Update a 'appliance.DiagSetting' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_setup_info(self):
        """Test case for update_appliance_setup_info

        Update a 'appliance.SetupInfo' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_upgrade(self):
        """Test case for update_appliance_upgrade

        Update a 'appliance.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_update_appliance_upgrade_policy(self):
        """Test case for update_appliance_upgrade_policy

        Update a 'appliance.UpgradePolicy' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
