# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.sdwan_api import SdwanApi  # noqa: E501


class TestSdwanApi(unittest.TestCase):
    """SdwanApi unit test stubs"""

    def setUp(self):
        self.api = SdwanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sdwan_profile(self):
        """Test case for create_sdwan_profile

        Create a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_create_sdwan_router_node(self):
        """Test case for create_sdwan_router_node

        Create a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_create_sdwan_router_policy(self):
        """Test case for create_sdwan_router_policy

        Create a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_sdwan_vmanage_account_policy(self):
        """Test case for create_sdwan_vmanage_account_policy

        Create a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_sdwan_profile(self):
        """Test case for delete_sdwan_profile

        Delete a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_delete_sdwan_router_node(self):
        """Test case for delete_sdwan_router_node

        Delete a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_delete_sdwan_router_policy(self):
        """Test case for delete_sdwan_router_policy

        Delete a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_sdwan_vmanage_account_policy(self):
        """Test case for delete_sdwan_vmanage_account_policy

        Delete a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_profile_by_moid(self):
        """Test case for get_sdwan_profile_by_moid

        Read a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_profile_list(self):
        """Test case for get_sdwan_profile_list

        Read a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_router_node_by_moid(self):
        """Test case for get_sdwan_router_node_by_moid

        Read a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_router_node_list(self):
        """Test case for get_sdwan_router_node_list

        Read a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_router_policy_by_moid(self):
        """Test case for get_sdwan_router_policy_by_moid

        Read a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_router_policy_list(self):
        """Test case for get_sdwan_router_policy_list

        Read a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_vmanage_account_policy_by_moid(self):
        """Test case for get_sdwan_vmanage_account_policy_by_moid

        Read a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_sdwan_vmanage_account_policy_list(self):
        """Test case for get_sdwan_vmanage_account_policy_list

        Read a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_sdwan_profile(self):
        """Test case for patch_sdwan_profile

        Update a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_patch_sdwan_router_node(self):
        """Test case for patch_sdwan_router_node

        Update a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_patch_sdwan_router_policy(self):
        """Test case for patch_sdwan_router_policy

        Update a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_sdwan_vmanage_account_policy(self):
        """Test case for patch_sdwan_vmanage_account_policy

        Update a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_sdwan_profile(self):
        """Test case for update_sdwan_profile

        Update a 'sdwan.Profile' resource.  # noqa: E501
        """
        pass

    def test_update_sdwan_router_node(self):
        """Test case for update_sdwan_router_node

        Update a 'sdwan.RouterNode' resource.  # noqa: E501
        """
        pass

    def test_update_sdwan_router_policy(self):
        """Test case for update_sdwan_router_policy

        Update a 'sdwan.RouterPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_sdwan_vmanage_account_policy(self):
        """Test case for update_sdwan_vmanage_account_policy

        Update a 'sdwan.VmanageAccountPolicy' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
