# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fabric_api import FabricApi  # noqa: E501


class TestFabricApi(unittest.TestCase):
    """FabricApi unit test stubs"""

    def setUp(self):
        self.api = FabricApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_fabric_eth_network_control_policy(self):
        """Test case for create_fabric_eth_network_control_policy

        Create a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_eth_network_policy(self):
        """Test case for create_fabric_eth_network_policy

        Create a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_fc_network_policy(self):
        """Test case for create_fabric_fc_network_policy

        Create a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_fc_uplink_pc_role(self):
        """Test case for create_fabric_fc_uplink_pc_role

        Create a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_fc_uplink_role(self):
        """Test case for create_fabric_fc_uplink_role

        Create a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_fcoe_uplink_pc_role(self):
        """Test case for create_fabric_fcoe_uplink_pc_role

        Create a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_fcoe_uplink_role(self):
        """Test case for create_fabric_fcoe_uplink_role

        Create a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_pc_operation(self):
        """Test case for create_fabric_pc_operation

        Create a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_port_mode(self):
        """Test case for create_fabric_port_mode

        Create a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_port_operation(self):
        """Test case for create_fabric_port_operation

        Create a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_port_policy(self):
        """Test case for create_fabric_port_policy

        Create a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_qos_policy(self):
        """Test case for create_fabric_qos_policy

        Create a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_server_role(self):
        """Test case for create_fabric_server_role

        Create a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_switch_cluster_profile(self):
        """Test case for create_fabric_switch_cluster_profile

        Create a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_switch_profile(self):
        """Test case for create_fabric_switch_profile

        Create a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_uplink_pc_role(self):
        """Test case for create_fabric_uplink_pc_role

        Create a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_uplink_role(self):
        """Test case for create_fabric_uplink_role

        Create a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_vlan(self):
        """Test case for create_fabric_vlan

        Create a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_create_fabric_vsan(self):
        """Test case for create_fabric_vsan

        Create a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_eth_network_control_policy(self):
        """Test case for delete_fabric_eth_network_control_policy

        Delete a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_eth_network_policy(self):
        """Test case for delete_fabric_eth_network_policy

        Delete a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_fc_network_policy(self):
        """Test case for delete_fabric_fc_network_policy

        Delete a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_fc_uplink_pc_role(self):
        """Test case for delete_fabric_fc_uplink_pc_role

        Delete a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_fc_uplink_role(self):
        """Test case for delete_fabric_fc_uplink_role

        Delete a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_fcoe_uplink_pc_role(self):
        """Test case for delete_fabric_fcoe_uplink_pc_role

        Delete a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_fcoe_uplink_role(self):
        """Test case for delete_fabric_fcoe_uplink_role

        Delete a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_pc_operation(self):
        """Test case for delete_fabric_pc_operation

        Delete a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_port_mode(self):
        """Test case for delete_fabric_port_mode

        Delete a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_port_operation(self):
        """Test case for delete_fabric_port_operation

        Delete a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_port_policy(self):
        """Test case for delete_fabric_port_policy

        Delete a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_qos_policy(self):
        """Test case for delete_fabric_qos_policy

        Delete a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_server_role(self):
        """Test case for delete_fabric_server_role

        Delete a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_switch_cluster_profile(self):
        """Test case for delete_fabric_switch_cluster_profile

        Delete a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_switch_profile(self):
        """Test case for delete_fabric_switch_profile

        Delete a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_uplink_pc_role(self):
        """Test case for delete_fabric_uplink_pc_role

        Delete a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_uplink_role(self):
        """Test case for delete_fabric_uplink_role

        Delete a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_vlan(self):
        """Test case for delete_fabric_vlan

        Delete a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_delete_fabric_vsan(self):
        """Test case for delete_fabric_vsan

        Delete a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_change_detail_by_moid(self):
        """Test case for get_fabric_config_change_detail_by_moid

        Read a 'fabric.ConfigChangeDetail' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_change_detail_list(self):
        """Test case for get_fabric_config_change_detail_list

        Read a 'fabric.ConfigChangeDetail' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_result_by_moid(self):
        """Test case for get_fabric_config_result_by_moid

        Read a 'fabric.ConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_result_entry_by_moid(self):
        """Test case for get_fabric_config_result_entry_by_moid

        Read a 'fabric.ConfigResultEntry' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_result_entry_list(self):
        """Test case for get_fabric_config_result_entry_list

        Read a 'fabric.ConfigResultEntry' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_config_result_list(self):
        """Test case for get_fabric_config_result_list

        Read a 'fabric.ConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_eth_network_control_policy_by_moid(self):
        """Test case for get_fabric_eth_network_control_policy_by_moid

        Read a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_eth_network_control_policy_list(self):
        """Test case for get_fabric_eth_network_control_policy_list

        Read a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_eth_network_policy_by_moid(self):
        """Test case for get_fabric_eth_network_policy_by_moid

        Read a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_eth_network_policy_list(self):
        """Test case for get_fabric_eth_network_policy_list

        Read a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_network_policy_by_moid(self):
        """Test case for get_fabric_fc_network_policy_by_moid

        Read a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_network_policy_list(self):
        """Test case for get_fabric_fc_network_policy_list

        Read a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_uplink_pc_role_by_moid(self):
        """Test case for get_fabric_fc_uplink_pc_role_by_moid

        Read a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_uplink_pc_role_list(self):
        """Test case for get_fabric_fc_uplink_pc_role_list

        Read a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_uplink_role_by_moid(self):
        """Test case for get_fabric_fc_uplink_role_by_moid

        Read a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fc_uplink_role_list(self):
        """Test case for get_fabric_fc_uplink_role_list

        Read a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fcoe_uplink_pc_role_by_moid(self):
        """Test case for get_fabric_fcoe_uplink_pc_role_by_moid

        Read a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fcoe_uplink_pc_role_list(self):
        """Test case for get_fabric_fcoe_uplink_pc_role_list

        Read a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fcoe_uplink_role_by_moid(self):
        """Test case for get_fabric_fcoe_uplink_role_by_moid

        Read a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_fcoe_uplink_role_list(self):
        """Test case for get_fabric_fcoe_uplink_role_list

        Read a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_pc_member_by_moid(self):
        """Test case for get_fabric_pc_member_by_moid

        Read a 'fabric.PcMember' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_pc_member_list(self):
        """Test case for get_fabric_pc_member_list

        Read a 'fabric.PcMember' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_pc_operation_by_moid(self):
        """Test case for get_fabric_pc_operation_by_moid

        Read a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_pc_operation_list(self):
        """Test case for get_fabric_pc_operation_list

        Read a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_mode_by_moid(self):
        """Test case for get_fabric_port_mode_by_moid

        Read a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_mode_list(self):
        """Test case for get_fabric_port_mode_list

        Read a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_operation_by_moid(self):
        """Test case for get_fabric_port_operation_by_moid

        Read a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_operation_list(self):
        """Test case for get_fabric_port_operation_list

        Read a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_policy_by_moid(self):
        """Test case for get_fabric_port_policy_by_moid

        Read a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_port_policy_list(self):
        """Test case for get_fabric_port_policy_list

        Read a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_qos_policy_by_moid(self):
        """Test case for get_fabric_qos_policy_by_moid

        Read a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_qos_policy_list(self):
        """Test case for get_fabric_qos_policy_list

        Read a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_server_role_by_moid(self):
        """Test case for get_fabric_server_role_by_moid

        Read a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_server_role_list(self):
        """Test case for get_fabric_server_role_list

        Read a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_switch_cluster_profile_by_moid(self):
        """Test case for get_fabric_switch_cluster_profile_by_moid

        Read a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_switch_cluster_profile_list(self):
        """Test case for get_fabric_switch_cluster_profile_list

        Read a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_switch_profile_by_moid(self):
        """Test case for get_fabric_switch_profile_by_moid

        Read a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_switch_profile_list(self):
        """Test case for get_fabric_switch_profile_list

        Read a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_uplink_pc_role_by_moid(self):
        """Test case for get_fabric_uplink_pc_role_by_moid

        Read a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_uplink_pc_role_list(self):
        """Test case for get_fabric_uplink_pc_role_list

        Read a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_uplink_role_by_moid(self):
        """Test case for get_fabric_uplink_role_by_moid

        Read a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_uplink_role_list(self):
        """Test case for get_fabric_uplink_role_list

        Read a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_vlan_by_moid(self):
        """Test case for get_fabric_vlan_by_moid

        Read a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_vlan_list(self):
        """Test case for get_fabric_vlan_list

        Read a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_vsan_by_moid(self):
        """Test case for get_fabric_vsan_by_moid

        Read a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass

    def test_get_fabric_vsan_list(self):
        """Test case for get_fabric_vsan_list

        Read a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_eth_network_control_policy(self):
        """Test case for patch_fabric_eth_network_control_policy

        Update a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_eth_network_policy(self):
        """Test case for patch_fabric_eth_network_policy

        Update a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_fc_network_policy(self):
        """Test case for patch_fabric_fc_network_policy

        Update a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_fc_uplink_pc_role(self):
        """Test case for patch_fabric_fc_uplink_pc_role

        Update a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_fc_uplink_role(self):
        """Test case for patch_fabric_fc_uplink_role

        Update a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_fcoe_uplink_pc_role(self):
        """Test case for patch_fabric_fcoe_uplink_pc_role

        Update a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_fcoe_uplink_role(self):
        """Test case for patch_fabric_fcoe_uplink_role

        Update a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_pc_operation(self):
        """Test case for patch_fabric_pc_operation

        Update a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_port_mode(self):
        """Test case for patch_fabric_port_mode

        Update a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_port_operation(self):
        """Test case for patch_fabric_port_operation

        Update a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_port_policy(self):
        """Test case for patch_fabric_port_policy

        Update a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_qos_policy(self):
        """Test case for patch_fabric_qos_policy

        Update a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_server_role(self):
        """Test case for patch_fabric_server_role

        Update a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_switch_cluster_profile(self):
        """Test case for patch_fabric_switch_cluster_profile

        Update a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_switch_profile(self):
        """Test case for patch_fabric_switch_profile

        Update a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_uplink_pc_role(self):
        """Test case for patch_fabric_uplink_pc_role

        Update a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_uplink_role(self):
        """Test case for patch_fabric_uplink_role

        Update a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_vlan(self):
        """Test case for patch_fabric_vlan

        Update a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_patch_fabric_vsan(self):
        """Test case for patch_fabric_vsan

        Update a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_eth_network_control_policy(self):
        """Test case for update_fabric_eth_network_control_policy

        Update a 'fabric.EthNetworkControlPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_eth_network_policy(self):
        """Test case for update_fabric_eth_network_policy

        Update a 'fabric.EthNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_fc_network_policy(self):
        """Test case for update_fabric_fc_network_policy

        Update a 'fabric.FcNetworkPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_fc_uplink_pc_role(self):
        """Test case for update_fabric_fc_uplink_pc_role

        Update a 'fabric.FcUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_fc_uplink_role(self):
        """Test case for update_fabric_fc_uplink_role

        Update a 'fabric.FcUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_fcoe_uplink_pc_role(self):
        """Test case for update_fabric_fcoe_uplink_pc_role

        Update a 'fabric.FcoeUplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_fcoe_uplink_role(self):
        """Test case for update_fabric_fcoe_uplink_role

        Update a 'fabric.FcoeUplinkRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_pc_operation(self):
        """Test case for update_fabric_pc_operation

        Update a 'fabric.PcOperation' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_port_mode(self):
        """Test case for update_fabric_port_mode

        Update a 'fabric.PortMode' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_port_operation(self):
        """Test case for update_fabric_port_operation

        Update a 'fabric.PortOperation' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_port_policy(self):
        """Test case for update_fabric_port_policy

        Update a 'fabric.PortPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_qos_policy(self):
        """Test case for update_fabric_qos_policy

        Update a 'fabric.QosPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_server_role(self):
        """Test case for update_fabric_server_role

        Update a 'fabric.ServerRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_switch_cluster_profile(self):
        """Test case for update_fabric_switch_cluster_profile

        Update a 'fabric.SwitchClusterProfile' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_switch_profile(self):
        """Test case for update_fabric_switch_profile

        Update a 'fabric.SwitchProfile' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_uplink_pc_role(self):
        """Test case for update_fabric_uplink_pc_role

        Update a 'fabric.UplinkPcRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_uplink_role(self):
        """Test case for update_fabric_uplink_role

        Update a 'fabric.UplinkRole' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_vlan(self):
        """Test case for update_fabric_vlan

        Update a 'fabric.Vlan' resource.  # noqa: E501
        """
        pass

    def test_update_fabric_vsan(self):
        """Test case for update_fabric_vsan

        Update a 'fabric.Vsan' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
