# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.firmware_api import FirmwareApi  # noqa: E501


class TestFirmwareApi(unittest.TestCase):
    """FirmwareApi unit test stubs"""

    def setUp(self):
        self.api = FirmwareApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_firmware_bios_descriptor(self):
        """Test case for create_firmware_bios_descriptor

        Create a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_board_controller_descriptor(self):
        """Test case for create_firmware_board_controller_descriptor

        Create a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_chassis_upgrade(self):
        """Test case for create_firmware_chassis_upgrade

        Create a 'firmware.ChassisUpgrade' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_cimc_descriptor(self):
        """Test case for create_firmware_cimc_descriptor

        Create a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_dimm_descriptor(self):
        """Test case for create_firmware_dimm_descriptor

        Create a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_distributable(self):
        """Test case for create_firmware_distributable

        Create a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_drive_descriptor(self):
        """Test case for create_firmware_drive_descriptor

        Create a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_driver_distributable(self):
        """Test case for create_firmware_driver_distributable

        Create a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_eula(self):
        """Test case for create_firmware_eula

        Create a 'firmware.Eula' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_gpu_descriptor(self):
        """Test case for create_firmware_gpu_descriptor

        Create a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_hba_descriptor(self):
        """Test case for create_firmware_hba_descriptor

        Create a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_iom_descriptor(self):
        """Test case for create_firmware_iom_descriptor

        Create a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_mswitch_descriptor(self):
        """Test case for create_firmware_mswitch_descriptor

        Create a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_nxos_descriptor(self):
        """Test case for create_firmware_nxos_descriptor

        Create a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_pcie_descriptor(self):
        """Test case for create_firmware_pcie_descriptor

        Create a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_psu_descriptor(self):
        """Test case for create_firmware_psu_descriptor

        Create a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_sas_expander_descriptor(self):
        """Test case for create_firmware_sas_expander_descriptor

        Create a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_server_configuration_utility_distributable(self):
        """Test case for create_firmware_server_configuration_utility_distributable

        Create a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_storage_controller_descriptor(self):
        """Test case for create_firmware_storage_controller_descriptor

        Create a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_switch_upgrade(self):
        """Test case for create_firmware_switch_upgrade

        Create a 'firmware.SwitchUpgrade' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_upgrade(self):
        """Test case for create_firmware_upgrade

        Create a 'firmware.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_create_firmware_upgrade_impact(self):
        """Test case for create_firmware_upgrade_impact

        Create a 'firmware.UpgradeImpact' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_bios_descriptor(self):
        """Test case for delete_firmware_bios_descriptor

        Delete a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_board_controller_descriptor(self):
        """Test case for delete_firmware_board_controller_descriptor

        Delete a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_chassis_upgrade(self):
        """Test case for delete_firmware_chassis_upgrade

        Delete a 'firmware.ChassisUpgrade' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_cimc_descriptor(self):
        """Test case for delete_firmware_cimc_descriptor

        Delete a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_dimm_descriptor(self):
        """Test case for delete_firmware_dimm_descriptor

        Delete a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_distributable(self):
        """Test case for delete_firmware_distributable

        Delete a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_drive_descriptor(self):
        """Test case for delete_firmware_drive_descriptor

        Delete a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_driver_distributable(self):
        """Test case for delete_firmware_driver_distributable

        Delete a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_gpu_descriptor(self):
        """Test case for delete_firmware_gpu_descriptor

        Delete a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_hba_descriptor(self):
        """Test case for delete_firmware_hba_descriptor

        Delete a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_iom_descriptor(self):
        """Test case for delete_firmware_iom_descriptor

        Delete a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_mswitch_descriptor(self):
        """Test case for delete_firmware_mswitch_descriptor

        Delete a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_nxos_descriptor(self):
        """Test case for delete_firmware_nxos_descriptor

        Delete a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_pcie_descriptor(self):
        """Test case for delete_firmware_pcie_descriptor

        Delete a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_psu_descriptor(self):
        """Test case for delete_firmware_psu_descriptor

        Delete a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_sas_expander_descriptor(self):
        """Test case for delete_firmware_sas_expander_descriptor

        Delete a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_server_configuration_utility_distributable(self):
        """Test case for delete_firmware_server_configuration_utility_distributable

        Delete a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_storage_controller_descriptor(self):
        """Test case for delete_firmware_storage_controller_descriptor

        Delete a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_switch_upgrade(self):
        """Test case for delete_firmware_switch_upgrade

        Delete a 'firmware.SwitchUpgrade' resource.  # noqa: E501
        """
        pass

    def test_delete_firmware_upgrade(self):
        """Test case for delete_firmware_upgrade

        Delete a 'firmware.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_bios_descriptor_by_moid(self):
        """Test case for get_firmware_bios_descriptor_by_moid

        Read a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_bios_descriptor_list(self):
        """Test case for get_firmware_bios_descriptor_list

        Read a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_board_controller_descriptor_by_moid(self):
        """Test case for get_firmware_board_controller_descriptor_by_moid

        Read a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_board_controller_descriptor_list(self):
        """Test case for get_firmware_board_controller_descriptor_list

        Read a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_chassis_upgrade_by_moid(self):
        """Test case for get_firmware_chassis_upgrade_by_moid

        Read a 'firmware.ChassisUpgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_chassis_upgrade_list(self):
        """Test case for get_firmware_chassis_upgrade_list

        Read a 'firmware.ChassisUpgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_cimc_descriptor_by_moid(self):
        """Test case for get_firmware_cimc_descriptor_by_moid

        Read a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_cimc_descriptor_list(self):
        """Test case for get_firmware_cimc_descriptor_list

        Read a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_dimm_descriptor_by_moid(self):
        """Test case for get_firmware_dimm_descriptor_by_moid

        Read a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_dimm_descriptor_list(self):
        """Test case for get_firmware_dimm_descriptor_list

        Read a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_distributable_by_moid(self):
        """Test case for get_firmware_distributable_by_moid

        Read a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_distributable_list(self):
        """Test case for get_firmware_distributable_list

        Read a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_distributable_meta_by_moid(self):
        """Test case for get_firmware_distributable_meta_by_moid

        Read a 'firmware.DistributableMeta' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_distributable_meta_list(self):
        """Test case for get_firmware_distributable_meta_list

        Read a 'firmware.DistributableMeta' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_drive_descriptor_by_moid(self):
        """Test case for get_firmware_drive_descriptor_by_moid

        Read a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_drive_descriptor_list(self):
        """Test case for get_firmware_drive_descriptor_list

        Read a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_driver_distributable_by_moid(self):
        """Test case for get_firmware_driver_distributable_by_moid

        Read a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_driver_distributable_list(self):
        """Test case for get_firmware_driver_distributable_list

        Read a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_eula_by_moid(self):
        """Test case for get_firmware_eula_by_moid

        Read a 'firmware.Eula' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_eula_list(self):
        """Test case for get_firmware_eula_list

        Read a 'firmware.Eula' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_firmware_summary_by_moid(self):
        """Test case for get_firmware_firmware_summary_by_moid

        Read a 'firmware.FirmwareSummary' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_firmware_summary_list(self):
        """Test case for get_firmware_firmware_summary_list

        Read a 'firmware.FirmwareSummary' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_gpu_descriptor_by_moid(self):
        """Test case for get_firmware_gpu_descriptor_by_moid

        Read a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_gpu_descriptor_list(self):
        """Test case for get_firmware_gpu_descriptor_list

        Read a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_hba_descriptor_by_moid(self):
        """Test case for get_firmware_hba_descriptor_by_moid

        Read a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_hba_descriptor_list(self):
        """Test case for get_firmware_hba_descriptor_list

        Read a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_iom_descriptor_by_moid(self):
        """Test case for get_firmware_iom_descriptor_by_moid

        Read a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_iom_descriptor_list(self):
        """Test case for get_firmware_iom_descriptor_list

        Read a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_mswitch_descriptor_by_moid(self):
        """Test case for get_firmware_mswitch_descriptor_by_moid

        Read a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_mswitch_descriptor_list(self):
        """Test case for get_firmware_mswitch_descriptor_list

        Read a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_nxos_descriptor_by_moid(self):
        """Test case for get_firmware_nxos_descriptor_by_moid

        Read a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_nxos_descriptor_list(self):
        """Test case for get_firmware_nxos_descriptor_list

        Read a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_pcie_descriptor_by_moid(self):
        """Test case for get_firmware_pcie_descriptor_by_moid

        Read a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_pcie_descriptor_list(self):
        """Test case for get_firmware_pcie_descriptor_list

        Read a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_psu_descriptor_by_moid(self):
        """Test case for get_firmware_psu_descriptor_by_moid

        Read a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_psu_descriptor_list(self):
        """Test case for get_firmware_psu_descriptor_list

        Read a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_running_firmware_by_moid(self):
        """Test case for get_firmware_running_firmware_by_moid

        Read a 'firmware.RunningFirmware' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_running_firmware_list(self):
        """Test case for get_firmware_running_firmware_list

        Read a 'firmware.RunningFirmware' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_sas_expander_descriptor_by_moid(self):
        """Test case for get_firmware_sas_expander_descriptor_by_moid

        Read a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_sas_expander_descriptor_list(self):
        """Test case for get_firmware_sas_expander_descriptor_list

        Read a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_server_configuration_utility_distributable_by_moid(self):
        """Test case for get_firmware_server_configuration_utility_distributable_by_moid

        Read a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_server_configuration_utility_distributable_list(self):
        """Test case for get_firmware_server_configuration_utility_distributable_list

        Read a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_storage_controller_descriptor_by_moid(self):
        """Test case for get_firmware_storage_controller_descriptor_by_moid

        Read a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_storage_controller_descriptor_list(self):
        """Test case for get_firmware_storage_controller_descriptor_list

        Read a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_switch_upgrade_by_moid(self):
        """Test case for get_firmware_switch_upgrade_by_moid

        Read a 'firmware.SwitchUpgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_switch_upgrade_list(self):
        """Test case for get_firmware_switch_upgrade_list

        Read a 'firmware.SwitchUpgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_by_moid(self):
        """Test case for get_firmware_upgrade_by_moid

        Read a 'firmware.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_impact_status_by_moid(self):
        """Test case for get_firmware_upgrade_impact_status_by_moid

        Read a 'firmware.UpgradeImpactStatus' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_impact_status_list(self):
        """Test case for get_firmware_upgrade_impact_status_list

        Read a 'firmware.UpgradeImpactStatus' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_list(self):
        """Test case for get_firmware_upgrade_list

        Read a 'firmware.Upgrade' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_status_by_moid(self):
        """Test case for get_firmware_upgrade_status_by_moid

        Read a 'firmware.UpgradeStatus' resource.  # noqa: E501
        """
        pass

    def test_get_firmware_upgrade_status_list(self):
        """Test case for get_firmware_upgrade_status_list

        Read a 'firmware.UpgradeStatus' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_bios_descriptor(self):
        """Test case for patch_firmware_bios_descriptor

        Update a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_board_controller_descriptor(self):
        """Test case for patch_firmware_board_controller_descriptor

        Update a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_cimc_descriptor(self):
        """Test case for patch_firmware_cimc_descriptor

        Update a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_dimm_descriptor(self):
        """Test case for patch_firmware_dimm_descriptor

        Update a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_distributable(self):
        """Test case for patch_firmware_distributable

        Update a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_drive_descriptor(self):
        """Test case for patch_firmware_drive_descriptor

        Update a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_driver_distributable(self):
        """Test case for patch_firmware_driver_distributable

        Update a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_gpu_descriptor(self):
        """Test case for patch_firmware_gpu_descriptor

        Update a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_hba_descriptor(self):
        """Test case for patch_firmware_hba_descriptor

        Update a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_iom_descriptor(self):
        """Test case for patch_firmware_iom_descriptor

        Update a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_mswitch_descriptor(self):
        """Test case for patch_firmware_mswitch_descriptor

        Update a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_nxos_descriptor(self):
        """Test case for patch_firmware_nxos_descriptor

        Update a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_pcie_descriptor(self):
        """Test case for patch_firmware_pcie_descriptor

        Update a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_psu_descriptor(self):
        """Test case for patch_firmware_psu_descriptor

        Update a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_running_firmware(self):
        """Test case for patch_firmware_running_firmware

        Update a 'firmware.RunningFirmware' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_sas_expander_descriptor(self):
        """Test case for patch_firmware_sas_expander_descriptor

        Update a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_server_configuration_utility_distributable(self):
        """Test case for patch_firmware_server_configuration_utility_distributable

        Update a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_patch_firmware_storage_controller_descriptor(self):
        """Test case for patch_firmware_storage_controller_descriptor

        Update a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_bios_descriptor(self):
        """Test case for update_firmware_bios_descriptor

        Update a 'firmware.BiosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_board_controller_descriptor(self):
        """Test case for update_firmware_board_controller_descriptor

        Update a 'firmware.BoardControllerDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_cimc_descriptor(self):
        """Test case for update_firmware_cimc_descriptor

        Update a 'firmware.CimcDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_dimm_descriptor(self):
        """Test case for update_firmware_dimm_descriptor

        Update a 'firmware.DimmDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_distributable(self):
        """Test case for update_firmware_distributable

        Update a 'firmware.Distributable' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_drive_descriptor(self):
        """Test case for update_firmware_drive_descriptor

        Update a 'firmware.DriveDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_driver_distributable(self):
        """Test case for update_firmware_driver_distributable

        Update a 'firmware.DriverDistributable' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_gpu_descriptor(self):
        """Test case for update_firmware_gpu_descriptor

        Update a 'firmware.GpuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_hba_descriptor(self):
        """Test case for update_firmware_hba_descriptor

        Update a 'firmware.HbaDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_iom_descriptor(self):
        """Test case for update_firmware_iom_descriptor

        Update a 'firmware.IomDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_mswitch_descriptor(self):
        """Test case for update_firmware_mswitch_descriptor

        Update a 'firmware.MswitchDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_nxos_descriptor(self):
        """Test case for update_firmware_nxos_descriptor

        Update a 'firmware.NxosDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_pcie_descriptor(self):
        """Test case for update_firmware_pcie_descriptor

        Update a 'firmware.PcieDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_psu_descriptor(self):
        """Test case for update_firmware_psu_descriptor

        Update a 'firmware.PsuDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_running_firmware(self):
        """Test case for update_firmware_running_firmware

        Update a 'firmware.RunningFirmware' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_sas_expander_descriptor(self):
        """Test case for update_firmware_sas_expander_descriptor

        Update a 'firmware.SasExpanderDescriptor' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_server_configuration_utility_distributable(self):
        """Test case for update_firmware_server_configuration_utility_distributable

        Update a 'firmware.ServerConfigurationUtilityDistributable' resource.  # noqa: E501
        """
        pass

    def test_update_firmware_storage_controller_descriptor(self):
        """Test case for update_firmware_storage_controller_descriptor

        Update a 'firmware.StorageControllerDescriptor' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
