# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.memory_api import MemoryApi  # noqa: E501


class TestMemoryApi(unittest.TestCase):
    """MemoryApi unit test stubs"""

    def setUp(self):
        self.api = MemoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_memory_persistent_memory_policy(self):
        """Test case for create_memory_persistent_memory_policy

        Create a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_delete_memory_persistent_memory_policy(self):
        """Test case for delete_memory_persistent_memory_policy

        Delete a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_memory_array_by_moid(self):
        """Test case for get_memory_array_by_moid

        Read a 'memory.Array' resource.  # noqa: E501
        """
        pass

    def test_get_memory_array_list(self):
        """Test case for get_memory_array_list

        Read a 'memory.Array' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_config_result_by_moid(self):
        """Test case for get_memory_persistent_memory_config_result_by_moid

        Read a 'memory.PersistentMemoryConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_config_result_list(self):
        """Test case for get_memory_persistent_memory_config_result_list

        Read a 'memory.PersistentMemoryConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_configuration_by_moid(self):
        """Test case for get_memory_persistent_memory_configuration_by_moid

        Read a 'memory.PersistentMemoryConfiguration' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_configuration_list(self):
        """Test case for get_memory_persistent_memory_configuration_list

        Read a 'memory.PersistentMemoryConfiguration' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_namespace_by_moid(self):
        """Test case for get_memory_persistent_memory_namespace_by_moid

        Read a 'memory.PersistentMemoryNamespace' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_namespace_config_result_by_moid(self):
        """Test case for get_memory_persistent_memory_namespace_config_result_by_moid

        Read a 'memory.PersistentMemoryNamespaceConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_namespace_config_result_list(self):
        """Test case for get_memory_persistent_memory_namespace_config_result_list

        Read a 'memory.PersistentMemoryNamespaceConfigResult' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_namespace_list(self):
        """Test case for get_memory_persistent_memory_namespace_list

        Read a 'memory.PersistentMemoryNamespace' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_policy_by_moid(self):
        """Test case for get_memory_persistent_memory_policy_by_moid

        Read a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_policy_list(self):
        """Test case for get_memory_persistent_memory_policy_list

        Read a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_region_by_moid(self):
        """Test case for get_memory_persistent_memory_region_by_moid

        Read a 'memory.PersistentMemoryRegion' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_region_list(self):
        """Test case for get_memory_persistent_memory_region_list

        Read a 'memory.PersistentMemoryRegion' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_unit_by_moid(self):
        """Test case for get_memory_persistent_memory_unit_by_moid

        Read a 'memory.PersistentMemoryUnit' resource.  # noqa: E501
        """
        pass

    def test_get_memory_persistent_memory_unit_list(self):
        """Test case for get_memory_persistent_memory_unit_list

        Read a 'memory.PersistentMemoryUnit' resource.  # noqa: E501
        """
        pass

    def test_get_memory_unit_by_moid(self):
        """Test case for get_memory_unit_by_moid

        Read a 'memory.Unit' resource.  # noqa: E501
        """
        pass

    def test_get_memory_unit_list(self):
        """Test case for get_memory_unit_list

        Read a 'memory.Unit' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_array(self):
        """Test case for patch_memory_array

        Update a 'memory.Array' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_config_result(self):
        """Test case for patch_memory_persistent_memory_config_result

        Update a 'memory.PersistentMemoryConfigResult' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_configuration(self):
        """Test case for patch_memory_persistent_memory_configuration

        Update a 'memory.PersistentMemoryConfiguration' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_namespace(self):
        """Test case for patch_memory_persistent_memory_namespace

        Update a 'memory.PersistentMemoryNamespace' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_namespace_config_result(self):
        """Test case for patch_memory_persistent_memory_namespace_config_result

        Update a 'memory.PersistentMemoryNamespaceConfigResult' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_policy(self):
        """Test case for patch_memory_persistent_memory_policy

        Update a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_region(self):
        """Test case for patch_memory_persistent_memory_region

        Update a 'memory.PersistentMemoryRegion' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_persistent_memory_unit(self):
        """Test case for patch_memory_persistent_memory_unit

        Update a 'memory.PersistentMemoryUnit' resource.  # noqa: E501
        """
        pass

    def test_patch_memory_unit(self):
        """Test case for patch_memory_unit

        Update a 'memory.Unit' resource.  # noqa: E501
        """
        pass

    def test_update_memory_array(self):
        """Test case for update_memory_array

        Update a 'memory.Array' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_config_result(self):
        """Test case for update_memory_persistent_memory_config_result

        Update a 'memory.PersistentMemoryConfigResult' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_configuration(self):
        """Test case for update_memory_persistent_memory_configuration

        Update a 'memory.PersistentMemoryConfiguration' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_namespace(self):
        """Test case for update_memory_persistent_memory_namespace

        Update a 'memory.PersistentMemoryNamespace' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_namespace_config_result(self):
        """Test case for update_memory_persistent_memory_namespace_config_result

        Update a 'memory.PersistentMemoryNamespaceConfigResult' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_policy(self):
        """Test case for update_memory_persistent_memory_policy

        Update a 'memory.PersistentMemoryPolicy' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_region(self):
        """Test case for update_memory_persistent_memory_region

        Update a 'memory.PersistentMemoryRegion' resource.  # noqa: E501
        """
        pass

    def test_update_memory_persistent_memory_unit(self):
        """Test case for update_memory_persistent_memory_unit

        Update a 'memory.PersistentMemoryUnit' resource.  # noqa: E501
        """
        pass

    def test_update_memory_unit(self):
        """Test case for update_memory_unit

        Update a 'memory.Unit' resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
