# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.appliance_image_bundle_relationship import ApplianceImageBundleRelationship
    from openapi_client.model.iam_account_relationship import IamAccountRelationship
    from openapi_client.model.onprem_upgrade_phase import OnpremUpgradePhase
    globals()['ApplianceImageBundleRelationship'] = ApplianceImageBundleRelationship
    globals()['IamAccountRelationship'] = IamAccountRelationship
    globals()['OnpremUpgradePhase'] = OnpremUpgradePhase


class ApplianceUpgradeAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'active': (bool,),  # noqa: E501
            'auto_created': (bool,),  # noqa: E501
            'completed_phases': ([OnpremUpgradePhase],),  # noqa: E501
            'current_phase': (OnpremUpgradePhase,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'elapsed_time': (int,),  # noqa: E501
            'end_time': (datetime,),  # noqa: E501
            'error_code': (int,),  # noqa: E501
            'fingerprint': (str,),  # noqa: E501
            'is_rolling_back': (bool,),  # noqa: E501
            'messages': ([str],),  # noqa: E501
            'rollback_needed': (bool,),  # noqa: E501
            'rollback_phases': ([OnpremUpgradePhase],),  # noqa: E501
            'rollback_status': (str,),  # noqa: E501
            'services': ([str],),  # noqa: E501
            'start_time': (datetime,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'total_phases': (int,),  # noqa: E501
            'ui_packages': ([str],),  # noqa: E501
            'version': (str,),  # noqa: E501
            'account': (IamAccountRelationship,),  # noqa: E501
            'image_bundle': (ApplianceImageBundleRelationship,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'active': 'Active',  # noqa: E501
        'auto_created': 'AutoCreated',  # noqa: E501
        'completed_phases': 'CompletedPhases',  # noqa: E501
        'current_phase': 'CurrentPhase',  # noqa: E501
        'description': 'Description',  # noqa: E501
        'elapsed_time': 'ElapsedTime',  # noqa: E501
        'end_time': 'EndTime',  # noqa: E501
        'error_code': 'ErrorCode',  # noqa: E501
        'fingerprint': 'Fingerprint',  # noqa: E501
        'is_rolling_back': 'IsRollingBack',  # noqa: E501
        'messages': 'Messages',  # noqa: E501
        'rollback_needed': 'RollbackNeeded',  # noqa: E501
        'rollback_phases': 'RollbackPhases',  # noqa: E501
        'rollback_status': 'RollbackStatus',  # noqa: E501
        'services': 'Services',  # noqa: E501
        'start_time': 'StartTime',  # noqa: E501
        'status': 'Status',  # noqa: E501
        'total_phases': 'TotalPhases',  # noqa: E501
        'ui_packages': 'UiPackages',  # noqa: E501
        'version': 'Version',  # noqa: E501
        'account': 'Account',  # noqa: E501
        'image_bundle': 'ImageBundle',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ApplianceUpgradeAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            active (bool): Indicates if the software upgrade is active or not.. [optional]  # noqa: E501
            auto_created (bool): Indicates that the request was automatically created by the system.. [optional]  # noqa: E501
            completed_phases ([OnpremUpgradePhase]): [optional]  # noqa: E501
            current_phase (OnpremUpgradePhase): [optional]  # noqa: E501
            description (str): Description of the software upgrade.. [optional]  # noqa: E501
            elapsed_time (int): Elapsed time in seconds during the software upgrade.. [optional]  # noqa: E501
            end_time (datetime): End date of the software upgrade.. [optional]  # noqa: E501
            error_code (int): Error code for Intersight Appliance&#39;s software upgrade. In case of failure - this code will help decide if software upgrade can be retried.. [optional]  # noqa: E501
            fingerprint (str): Software upgrade manifest&#39;s fingerprint.. [optional]  # noqa: E501
            is_rolling_back (bool): Track if software upgrade is upgrading or rolling back.. [optional]  # noqa: E501
            messages ([str]): [optional]  # noqa: E501
            rollback_needed (bool): Track if rollback is needed.. [optional]  # noqa: E501
            rollback_phases ([OnpremUpgradePhase]): [optional]  # noqa: E501
            rollback_status (str): Status of the Intersight Appliance&#39;s software rollback status.. [optional]  # noqa: E501
            services ([str]): [optional]  # noqa: E501
            start_time (datetime): Start date of the software upgrade. UI can modify startTime to re-schedule an upgrade.. [optional]  # noqa: E501
            status (str): Status of the Intersight Appliance&#39;s software upgrade.. [optional]  # noqa: E501
            total_phases (int): TotalPhase represents the total number of the upgradePhases for one upgrade.. [optional]  # noqa: E501
            ui_packages ([str]): [optional]  # noqa: E501
            version (str): Software upgrade manifest&#39;s version.. [optional]  # noqa: E501
            account (IamAccountRelationship): [optional]  # noqa: E501
            image_bundle (ApplianceImageBundleRelationship): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
