# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.asset_cluster_member_relationship import AssetClusterMemberRelationship
    from openapi_client.model.asset_device_claim_relationship import AssetDeviceClaimRelationship
    from openapi_client.model.asset_device_configuration_relationship import AssetDeviceConfigurationRelationship
    from openapi_client.model.asset_device_registration_relationship import AssetDeviceRegistrationRelationship
    from openapi_client.model.asset_parent_connection_signature import AssetParentConnectionSignature
    from openapi_client.model.iam_account_relationship import IamAccountRelationship
    from openapi_client.model.iam_domain_group_relationship import IamDomainGroupRelationship
    from openapi_client.model.iam_user_relationship import IamUserRelationship
    globals()['AssetClusterMemberRelationship'] = AssetClusterMemberRelationship
    globals()['AssetDeviceClaimRelationship'] = AssetDeviceClaimRelationship
    globals()['AssetDeviceConfigurationRelationship'] = AssetDeviceConfigurationRelationship
    globals()['AssetDeviceRegistrationRelationship'] = AssetDeviceRegistrationRelationship
    globals()['AssetParentConnectionSignature'] = AssetParentConnectionSignature
    globals()['IamAccountRelationship'] = IamAccountRelationship
    globals()['IamDomainGroupRelationship'] = IamDomainGroupRelationship
    globals()['IamUserRelationship'] = IamUserRelationship


class AssetDeviceRegistrationAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('execution_mode',): {
            'EMPTY': "",
            'NORMAL': "Normal",
            'EMULATOR': "Emulator",
            'CONTAINEREMULATOR': "ContainerEmulator",
        },
        ('platform_type',): {
            'EMPTY': "",
            'APIC': "APIC",
            'DCNM': "DCNM",
            'UCSFI': "UCSFI",
            'UCSFIISM': "UCSFIISM",
            'IMC': "IMC",
            'IMCM4': "IMCM4",
            'IMCM5': "IMCM5",
            'UCSIOM': "UCSIOM",
            'HX': "HX",
            'HYPERFLEXAP': "HyperFlexAP",
            'UCSD': "UCSD",
            'INTERSIGHTAPPLIANCE': "IntersightAppliance",
            'PURESTORAGEFLASHARRAY': "PureStorageFlashArray",
            'NETAPPONTAP': "NetAppOntap",
            'EMCSCALEIO': "EmcScaleIo",
            'EMCVMAX': "EmcVmax",
            'EMCVPLEX': "EmcVplex",
            'EMCXTREMIO': "EmcXtremIo",
            'VMWAREVCENTER': "VmwareVcenter",
            'MICROSOFTHYPERV': "MicrosoftHyperV",
            'APPDYNAMICS': "AppDynamics",
            'DYNATRACE': "Dynatrace",
            'MICROSOFTSQLSERVER': "MicrosoftSqlServer",
            'KUBERNETES': "Kubernetes",
            'MICROSOFTAZURE': "MicrosoftAzure",
            'SERVICEENGINE': "ServiceEngine",
            'IMCBLADE': "IMCBlade",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'access_key_id': (str,),  # noqa: E501
            'claimed_by_user_name': (str,),  # noqa: E501
            'claimed_time': (datetime,),  # noqa: E501
            'device_hostname': ([str],),  # noqa: E501
            'device_ip_address': ([str],),  # noqa: E501
            'execution_mode': (str,),  # noqa: E501
            'parent_signature': (AssetParentConnectionSignature,),  # noqa: E501
            'pid': ([str],),  # noqa: E501
            'platform_type': (str,),  # noqa: E501
            'public_access_key': (str,),  # noqa: E501
            'read_only': (bool,),  # noqa: E501
            'serial': ([str],),  # noqa: E501
            'vendor': (str,),  # noqa: E501
            'account': (IamAccountRelationship,),  # noqa: E501
            'claimed_by_user': (IamUserRelationship,),  # noqa: E501
            'cluster_members': ([AssetClusterMemberRelationship], none_type,),  # noqa: E501
            'device_claim': (AssetDeviceClaimRelationship,),  # noqa: E501
            'device_configuration': (AssetDeviceConfigurationRelationship,),  # noqa: E501
            'domain_group': (IamDomainGroupRelationship,),  # noqa: E501
            'parent_connection': (AssetDeviceRegistrationRelationship,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'access_key_id': 'AccessKeyId',  # noqa: E501
        'claimed_by_user_name': 'ClaimedByUserName',  # noqa: E501
        'claimed_time': 'ClaimedTime',  # noqa: E501
        'device_hostname': 'DeviceHostname',  # noqa: E501
        'device_ip_address': 'DeviceIpAddress',  # noqa: E501
        'execution_mode': 'ExecutionMode',  # noqa: E501
        'parent_signature': 'ParentSignature',  # noqa: E501
        'pid': 'Pid',  # noqa: E501
        'platform_type': 'PlatformType',  # noqa: E501
        'public_access_key': 'PublicAccessKey',  # noqa: E501
        'read_only': 'ReadOnly',  # noqa: E501
        'serial': 'Serial',  # noqa: E501
        'vendor': 'Vendor',  # noqa: E501
        'account': 'Account',  # noqa: E501
        'claimed_by_user': 'ClaimedByUser',  # noqa: E501
        'cluster_members': 'ClusterMembers',  # noqa: E501
        'device_claim': 'DeviceClaim',  # noqa: E501
        'device_configuration': 'DeviceConfiguration',  # noqa: E501
        'domain_group': 'DomainGroup',  # noqa: E501
        'parent_connection': 'ParentConnection',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """AssetDeviceRegistrationAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            access_key_id (str): An identifier for the credential used by the device connector to authenticate with the Intersight web socket gateway.. [optional]  # noqa: E501
            claimed_by_user_name (str): The name of the user who claimed the device for the account.. [optional]  # noqa: E501
            claimed_time (datetime): The date and time at which the device was claimed to this account.. [optional]  # noqa: E501
            device_hostname ([str]): [optional]  # noqa: E501
            device_ip_address ([str]): [optional]  # noqa: E501
            execution_mode (str): Indicates if the platform is an actual device or an emulated device for testing, demos, etc. Permitted values are [Normal, Emulator, ContainerEmulator].. [optional] if omitted the server will use the default value of ""  # noqa: E501
            parent_signature (AssetParentConnectionSignature): [optional]  # noqa: E501
            pid ([str]): [optional]  # noqa: E501
            platform_type (str): The platform type on which device connector is executing.. [optional] if omitted the server will use the default value of ""  # noqa: E501
            public_access_key (str): The device connector&#39;s public key used by Intersight to authenticate a connection from the device connector. The public key is used to verify that the signature a device connector sends on connect has been signed by the connector&#39;s private key stored on the device&#39;s filesystem. Must be a PEM encoded RSA public key string.. [optional]  # noqa: E501
            read_only (bool): Flag reported by devices to indicate an administrator of the device has disabled management operations of the device connector and only monitoring is permitted.. [optional]  # noqa: E501
            serial ([str]): [optional]  # noqa: E501
            vendor (str): The vendor of the managed device.. [optional]  # noqa: E501
            account (IamAccountRelationship): [optional]  # noqa: E501
            claimed_by_user (IamUserRelationship): [optional]  # noqa: E501
            cluster_members ([AssetClusterMemberRelationship], none_type): An array of relationships to assetClusterMember resources.. [optional]  # noqa: E501
            device_claim (AssetDeviceClaimRelationship): [optional]  # noqa: E501
            device_configuration (AssetDeviceConfigurationRelationship): [optional]  # noqa: E501
            domain_group (IamDomainGroupRelationship): [optional]  # noqa: E501
            parent_connection (AssetDeviceRegistrationRelationship): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
