# coding: utf-8

"""
    Cisco Intersight

    Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-30T07:31:54Z.  # noqa: E501

    The version of the OpenAPI document: 1.0.9-1950
    Contact: intersight@cisco.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.iam_account_relationship import IamAccountRelationship
    from openapi_client.model.iam_o_auth_token_relationship import IamOAuthTokenRelationship
    from openapi_client.model.iam_permission_relationship import IamPermissionRelationship
    from openapi_client.model.iam_role_relationship import IamRoleRelationship
    from openapi_client.model.iam_user_relationship import IamUserRelationship
    globals()['IamAccountRelationship'] = IamAccountRelationship
    globals()['IamOAuthTokenRelationship'] = IamOAuthTokenRelationship
    globals()['IamPermissionRelationship'] = IamPermissionRelationship
    globals()['IamRoleRelationship'] = IamRoleRelationship
    globals()['IamUserRelationship'] = IamUserRelationship


class IamAppRegistrationAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('client_type',): {
            'PUBLIC': "public",
            'CONFIDENTIAL': "confidential",
        },
        ('grant_types',): {
            'AUTHORIZATION_CODE': "authorization_code",
            'REFRESH_TOKEN': "refresh_token",
            'CLIENT_CREDENTIALS': "client_credentials",
            'IMPLICIT': "implicit",
            'PASSWORD': "password",
            'URN:IETF:PARAMS:OAUTH:GRANT-TYPE:JWT-BEARER': "urn:ietf:params:oauth:grant-type:jwt-bearer",
            'URN:IETF:PARAMS:OAUTH:GRANT-TYPE:SAML2-BEARER': "urn:ietf:params:oauth:grant-type:saml2-bearer",
        },
        ('response_types',): {
            'CODE': "code",
            'TOKEN': "token",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'client_id': (str,),  # noqa: E501
            'client_name': (str,),  # noqa: E501
            'client_secret': (str,),  # noqa: E501
            'client_type': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'grant_types': ([str],),  # noqa: E501
            'redirect_uris': ([str],),  # noqa: E501
            'renew_client_secret': (bool,),  # noqa: E501
            'response_types': ([str],),  # noqa: E501
            'revocation_timestamp': (datetime,),  # noqa: E501
            'revoke': (bool,),  # noqa: E501
            'account': (IamAccountRelationship,),  # noqa: E501
            'oauth_tokens': ([IamOAuthTokenRelationship], none_type,),  # noqa: E501
            'permission': (IamPermissionRelationship,),  # noqa: E501
            'roles': ([IamRoleRelationship], none_type,),  # noqa: E501
            'user': (IamUserRelationship,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'client_id': 'ClientId',  # noqa: E501
        'client_name': 'ClientName',  # noqa: E501
        'client_secret': 'ClientSecret',  # noqa: E501
        'client_type': 'ClientType',  # noqa: E501
        'description': 'Description',  # noqa: E501
        'grant_types': 'GrantTypes',  # noqa: E501
        'redirect_uris': 'RedirectUris',  # noqa: E501
        'renew_client_secret': 'RenewClientSecret',  # noqa: E501
        'response_types': 'ResponseTypes',  # noqa: E501
        'revocation_timestamp': 'RevocationTimestamp',  # noqa: E501
        'revoke': 'Revoke',  # noqa: E501
        'account': 'Account',  # noqa: E501
        'oauth_tokens': 'OauthTokens',  # noqa: E501
        'permission': 'Permission',  # noqa: E501
        'roles': 'Roles',  # noqa: E501
        'user': 'User',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """IamAppRegistrationAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            client_id (str): A unique identifier for the OAuth2 client application. The client ID is auto-generated when the AppRegistration object is created.. [optional]  # noqa: E501
            client_name (str): App Registration name specified by user.. [optional]  # noqa: E501
            client_secret (str): The OAuth2 client secret. The value of this property is generated when grantType includes &#39;client-credentials&#39;. Otherwise, no client-secret is generated.. [optional]  # noqa: E501
            client_type (str): The type of the OAuth2 client (public or confidential), as specified in https://tools.ietf.org/html/rfc6749#section-2.1.. [optional] if omitted the server will use the default value of "public"  # noqa: E501
            description (str): Description of the application.. [optional]  # noqa: E501
            grant_types ([str]): [optional]  # noqa: E501
            redirect_uris ([str]): [optional]  # noqa: E501
            renew_client_secret (bool): Set value to true to renew the client-secret. Applicable to client_credentials grant type.. [optional]  # noqa: E501
            response_types ([str]): [optional]  # noqa: E501
            revocation_timestamp (datetime): Used to perform revocation for tokens of AppRegistration. Updated only internally is case Revoke property come from UI with value true. On each request with OAuth2 access token the CreationTime of the OAuth2 token will be compared to RevokationTimestamp of the corresponding App Registration.. [optional]  # noqa: E501
            revoke (bool): Used to trigger update the revocationTimestamp value. If UI sent updating request with the Revoke value is true, then update RevocationTimestamp.. [optional]  # noqa: E501
            account (IamAccountRelationship): [optional]  # noqa: E501
            oauth_tokens ([IamOAuthTokenRelationship], none_type): An array of relationships to iamOAuthToken resources.. [optional]  # noqa: E501
            permission (IamPermissionRelationship): [optional]  # noqa: E501
            roles ([IamRoleRelationship], none_type): An array of relationships to iamRole resources.. [optional]  # noqa: E501
            user (IamUserRelationship): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
